### ISSUE TITLE
Submit to addons.mozilla.org

### ISSUE THREAD

**Issue by andrewaylett** [akamai/akamai_developer_toolkit#55]
This looks like a really useful tool.  Can I ask that you package it for Firefox and submit it to https://addons.mozilla.org, please?

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

**Comment by akhilakamai** [comment]
That's awesome ! @ricky840 is this something you can help with?

**Comment by akhilakamai** [comment]
@andrewaylett out of curiosity, what features piqued your interest in the toolkit?

**Comment by javiergarza** [comment]
Closing this issue since all the people who initially created this extension are no longer at Akamai and it is unlikely they would be interested on porting it to Firefox. Feel free to comment here if anyone is interested on doing that.
