### ISSUE TITLE
enabled Chrome extension will prevent certain content to be shown (causing CORS issues)

### ISSUE THREAD

**Issue by pjungermann** [akamai/akamai_developer_toolkit#69]
example

Bitbucket Cloud search
- see https://jira.atlassian.com/browse/BCLOUD-19281
- the search page got blank due to CORS issues present only with the toolkit extension enabled

I need to disable the extension at the Chrome extension menu to make the issues go away. It was not enough to only disable features.

**Comment by akhiljay** [comment]
Hi @pjungermann , you can disable debug headers advertisement from within the extension. This is available under the Browser settings inside the debugging section. These debug headers is what caused some websites to not respond properly

**Comment by carlosnororis** [comment]
Issue has been resolved on v2.0.40.
