### ISSUE TITLE
Developer Toolkit Extension causing issues with Websites after Google Chrome 80 update

### ISSUE THREAD

**Issue by javiergarza** [akamai/akamai_developer_toolkit#70]
Seems [Google Chrome v80](https://www.chromestatus.com/features/schedule) (released on 2 Feb 2020) enforces [same-site cookies](https://blog.chromium.org/2019/10/developers-get-ready-for-new.html) that cause issues visiting Websites using this extension. So far I was not able to login to the console.platform.sh until I disabled the developer toolkit extension. I also have reports of other people not able to use mPulse dashboards. @akhiljay / @ricky840 do you have any recommendations?

**Comment by carlosnororis** [comment]
Issue has been resolved on v2.0.40.
