### ISSUE TITLE
Enabling RO Output breaks requests

### ISSUE THREAD

**Issue by renebaudisch** [akamai/akamai_developer_toolkit#71]
Using Opera:
![image](https://user-images.githubusercontent.com/15980546/81005842-dc218900-8e4e-11ea-9bf8-ddedd87315b4.png)

I even couldn't upload my screenshot here while the extension was active.

**Comment by akamaimike** [comment]
Hi Rene,

Thanks for reporting this issue on Opera. We are aware of the CORS header issues in several browsers for the Akamai Developer Toolkit for Google Chrome and Opera.

That said, the Akamai Developer Toolkit was developed as a side project by an Akamai employee who is no longer with Akamai and we are in process of addressing ownership internally. Apologies for the inconvenience.

I see that you are looking for Resource Optimizer feedback, have you tried the stand-alone Piez tool? Google Chrome link: https://chrome.google.com/webstore/detail/piez/npbccjkjemgagjioahfccljgnlkdleod?hl=en 

I ran https://www.computerbild.de with the Akamai Developer Toolkit and RO on and received the errors. But running the same RO on on Piez stand-alone, seemed to work properly.

I hope that helps. Please let us know if you have any further questions. 

Kind regards, Mike

**Comment by renebaudisch** [comment]
Ah, OK, I thought this plugin would be the better alternative because it offers more options, but in this case you maybe should take it off the shop...
