### ISSUE TITLE
security question

### ISSUE THREAD

**Issue by cmstroscio** [akamai/akamai_developer_toolkit#80]
Hey there, I've been finding this extension to be useful. Is there more detail on how the credentials are stored? We want to be sure that they are secure.

**Comment by akamaimike** [comment]
Late response but I took a look at the way the credentials are stored and they are being hashed. They are not being stored in plaintext inside the Google Chrome Extension directory.

**Comment by cmstroscio** [comment]
Great, thank you so much!
